---
- name: Ensure set td-agent config
  template: src=:etc:td-agent:td-agent.conf.j2 dest=/etc/td-agent/td-agent.conf owner=root group=root mode=0644

- name: Ensure stop td-agent
  service: name=td-agent state=stopped

- name: Ensure start td-agent
  service: name=td-agent state=started
