---
fluentd_application_type: nodejs
fluentd_log_type:
  access:
    name: access
    log_file: /var/log/nodejs/access.log
    pos_file: /etc/td-agent/pos/nodejs.access.log.pos
  error:
    name: error
    log_file: /var/log/nodejs/error.log
    pos_file: /etc/td-agent/pos/nodejs.error.log.pos
    tail_format:
      - format multiline
      - format_firstline /^\[(?:.|\n)*/
      - format1 /(?<message>((?:.|\n)*[^\n ]))/
